### ISSUE TITLE
404 page not found when accessing

### ISSUE THREAD

**Issue by ChrisDeh** [digineo/3cx_exporter#2]
When build the app the following way:
1. Changing config path to "/etc/3cx_exporter/config.json" inside main.go
2. go get github.com/digineo/3cx_exporter/exporter
3. go get github.com/prometheus/client_golang/prometheus
4. go get github.com/prometheus/client_golang/prometheus/promhttp
5. go build
6. creating config.json at the described path

When running the App from Shell and looking at Port 9523 the only response displayed is: "404 page not found"

**Comment by corny** [comment]
Did you try to access http://localhost:9523/metrics ?
We haven't setup up a root page yet.

**Comment by ChrisDeh** [comment]
Accessing the metrics page works. Prometheus polling is working fine.
